name: Go fmt, test and build

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'  # Adjust as needed

    - name: Cache Go modules
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Install golangci-lint
      uses: golangci/golangci-lint-action@v4
      with:
        version: latest

    - name: Run golangci-lint
      run: golangci-lint run ./...

    - name: Check formatting with gofmt
      run: |
        fmt_output=$(gofmt -l .)
        if [[ -n "$fmt_output" ]]; then
          echo "The following files are not formatted:"
          echo "$fmt_output"
          exit 1
        fi

    - name: Run tests
      run: |
        go test ./... -v -coverprofile=coverage.out
        go tool cover -func=coverage.out

    - name: Build
      run: |
        go build ./...
